# Site settings
title:          safak
description:    "personal blog"
url:            "https://safakferhatkaya.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Safak Ferhat Kaya
  url:          https://safakferhatkaya.github.io
  email:        safakferhatkaya@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec, vendor ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

remote_theme: chesterhow/tale
